/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:518503:
  appc.background(230);
} //_CODE_:window1:518503:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:227605:
  Len = (custom_slider1.getValueF());
} //_CODE_:custom_slider1:227605:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider2:396195:
  Diam = (custom_slider2.getValueF());
} //_CODE_:custom_slider2:396195:

public void custom_slider3_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider3:924459:
  Thic = custom_slider3.getValueF();
} //_CODE_:custom_slider3:924459:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:498902:
  d = 0;
  MP = getMP();
  loop();
  S = new Submarine(Diam,Len,Thic,MP,450,60+int(Diam),MaterialIndex);
} //_CODE_:button1:498902:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:274315:
  MaterialIndex = dropList1.getSelectedIndex();
} //_CODE_:dropList1:274315:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 290, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  custom_slider1 = new GCustomSlider(window1, 5, 45, 113, 33, "grey_blue");
  custom_slider1.setShowValue(true);
  custom_slider1.setShowLimits(true);
  custom_slider1.setLimits(40.0, 40.0, 80.0);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  custom_slider2 = new GCustomSlider(window1, 5, 111, 113, 33, "grey_blue");
  custom_slider2.setShowValue(true);
  custom_slider2.setShowLimits(true);
  custom_slider2.setLimits(18.0, 12.0, 24.0);
  custom_slider2.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider2.setOpaque(false);
  custom_slider2.addEventHandler(this, "custom_slider2_change1");
  custom_slider3 = new GCustomSlider(window1, 5, 180, 113, 33, "grey_blue");
  custom_slider3.setShowValue(true);
  custom_slider3.setShowLimits(true);
  custom_slider3.setLimits(15.0, 10.0, 25.0);
  custom_slider3.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider3.setOpaque(false);
  custom_slider3.addEventHandler(this, "custom_slider3_change1");
  label1 = new GLabel(window1, 5, 17, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Length (m)");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 5, 86, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Diameter (m)");
  label2.setOpaque(false);
  label3 = new GLabel(window1, 5, 153, 124, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Wall Thickness (cm)");
  label3.setOpaque(false);
  button1 = new GButton(window1, 85, 236, 80, 24);
  button1.setText("Dive");
  button1.addEventHandler(this, "button1_click1");
  dropList1 = new GDropList(window1, 137, 45, 90, 80, 3, 10);
  dropList1.setItems(loadStrings("list_274315"), 1);
  dropList1.addEventHandler(this, "dropList1_click1");
  label4 = new GLabel(window1, 137, 16, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Material");
  label4.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider custom_slider1; 
GCustomSlider custom_slider2; 
GCustomSlider custom_slider3; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GButton button1; 
GDropList dropList1; 
GLabel label4; 
